(define (problem part2)
  (:domain transport)
  (:objects truck1 truck2 package1 package2 location1 location2 location3 t1_s1 t2_s1 t2_s2 c1 c2 c3 c4 c5 c6)
  (:init
    (location location1)
    (location location2)
    (location location3)
    (package package1)
    (package package2)
    (truck truck1)
    (truck truck2)
    (storage t1_s1)
    (storage t2_s1)
    (storage t2_s2)
    (canister c1)
    (canister c2)
    (canister c3)
    (canister c4)
    (canister c5)
    (canister c6)
    (storage_free t1_s1)
    (storage_free t2_s1)
    (storage_free t2_s2)
    (truck_at_location truck1 location1)
    (truck_at_location truck2 location1)
    (storage_on_truck t1_s1 truck1)
    (storage_on_truck t2_s1 truck2)
    (storage_on_truck t2_s2 truck2)
    (package_at_location package1 location2)
    (package_at_location package2 location2)
    (location_to_location location1 location2)
    (location_to_location location2 location1)
    (location_to_location location1 location3)
    (location_to_location location3 location1)
    (canister_at_location c1 location1)
    (canister_at_location c2 location3)
    (canister_at_location c3 location3)
    (canister_at_location c4 location3)
    (canister_at_location c5 location3)
    (canister_at_location c6 location3)
  )
  (:goal
    (and
      (package_at_location package1 location3)
      (package_at_location package2 location3)
    )
  )
)
